### PR TITLE
Add API documentation

### PR DESCRIPTION
**Pull request by dstansby**
Fixes https://github.com/quantumjot/BayesianTracker/issues/102. @quantumjot I've only added `btrack`, `btrack.types` and `btrack.models` to the docs as they seem like the main user facing API? Is there anything else that should be added or removed?

### CODE REVIEW

**Comment by quantumjot** [comment]
Might be worth including some of the import and utils functions too, e.g. 

- `dataio.import_CSV`
- `utils.segmentation_to_objects`

**Comment by dstansby** [comment]
👍 I added those in. In general it's best to be conservative with what's included, as once users start using functions/classes it is tricky to change API without annoying them 😄

**Comment by quantumjot** [comment]
Just to revisit this - I don't see the API documentation on RTD for main branch.

**Comment by dstansby** [comment]
That might be because the default branch on RTD is still set to `master` - can you check in the settings at https://readthedocs.org/projects/btrack/ and change the default branch to `main` if it's not already set to that?

**Comment by quantumjot** [comment]
That looks like it worked - thanks @dstansby !

**Pull request merged**
